const userInfoCons={
    START_GET_USER_INFO:'START_GET_USER_INFO',
    SUCCESS_GET_USER_INFO:'SUCCESS_GET_USER_INFO',
    FAILED_GET_USER_INFO:' FAILED_GET_USER_INFO'
}

const requestsUserCons={
        START_GET_REQUESTS_USER:'START_GET_REQUESTS_USER',
        SUCCESS_GET_REQUESTS_USER:'SUCCESS_GET_REQUESTS_USER',
        FAILED_GET_REQUESTS_USER:'FAILED_GET_REQUESTS_USER'
}

const usersAdmincons={
    START_GET_USERS_ADMIN:"START_GET_USERS_ADMIN",
    SUCCESS_GET_USERS_ADMIN:'SUCCESS_GET_USERS_ADMIN',
    FAILED_GET_USERS_ADMIN:'FAILED_GET_USERS_ADMIN'
}


const productsAdmincons={
    START_GET_PRODUCTS_ADMIN:"START_GET_PRODUCTS_ADMIN",
    SUCCESS_GET_PRODUCTS_ADMIN:'SUCCESS_GET_PRODUCTS_ADMIN',
    FAILED_GET_PRODUCTS_ADMIN:'FAILED_GET_PRODUCTS_ADMIN'
}

const CONSTANTS={
...userInfoCons,
...requestsUserCons,
...usersAdmincons,
...productsAdmincons

}

export  default CONSTANTS